-- This file was automatically generated by AlyxLib.

-- alyxlib can only run on server
if IsServer() then
    -- Load alyxlib before using it, in case this mod loads before the alyxlib mod.
    require("alyxlib.init")

    -- execute code or load mod libraries here
    require("auto_pickup.convars")
    require("auto_pickup.debug_menu")
    require("auto_pickup.main")
end